### PR TITLE
Change the way the package relationship attributes are evaluated

### PR DESCRIPTION
**Pull request by TomyLobo**
The change to the recommends line fixes --deb-recommends for me.

The rest of the changes are untested.

### CODE REVIEW

**Comment by jordansissel** [comment]
I agree with this change, but I think the commit message confuses me - it feels like this really fixes a bug (empty lists). "Change the way" is a bit confusing. I'll merge this by hand and update the commit message. <3

**Comment by jordansissel** [comment]
Merged as 0b104c260501cc7f09e85e8418fa2fdfb7a7e039 into master. Thank you!

**Comment by TomyLobo** [comment]
I didn't fully know what i was doing there tbh, i just made everything look the way it worked for the "recommends" line :)

**Comment by jordansissel** [comment]
@TomyLobo no worries! Teamwork solves all :)

**Pull request closed without merging**
