### PR TITLE
Remove breaking else in template deb postinst script

### PR DESCRIPTION
**Pull request by guohaolee**
Hi, It seems like there's a bug when running multiple SystemD restart.  Its caused by the **else** which is not supposed to be there. Removing the **else** helps to fix the issue on multiple systemd service restart

### CODE REVIEW

**Comment by jordansissel** [comment]
This change looks good, though I haven't tested. Please advise in a new issue if anything fails - I'll merge as-is now. :)

**Comment by jordansissel** [comment]
There's merge conflicts on this PR, and I'm not entirely sure how to resolve them.  There are multiple authors on changes to one file, can you advise?

```
% git diff $(git merge-base master HEAD)
diff --git a/templates/deb/postinst_upgrade.sh.erb b/templates/deb/postinst_upgrade.sh.erb
index 0cdbcf0..072727b 100644
--- a/templates/deb/postinst_upgrade.sh.erb
+++ b/templates/deb/postinst_upgrade.sh.erb
@@ -13,7 +13,7 @@ after_upgrade() {
 systemctl --system daemon-reload >/dev/null || true
 debsystemctl=$(command -v deb-systemd-invoke || echo systemctl)
 <% attributes[:deb_systemd].each do |service| -%>
-if ! systemctl is-enabled <%= service %> >/dev/null
+if ! systemctl is-enabled <%= service %> >/dev/null
 then
 <% if attributes[:deb_systemd_enable?]-%>
     systemctl enable <%= service %> >/dev/null || true
@@ -22,12 +22,18 @@ then
     $debsystemctl start <%= service %> >/dev/null || true
 <% end -%>
 <% if attributes[:deb_systemd_restart_after_upgrade?] -%>
+    $debsystemctl restart <%= service %> >/dev/null || true
+<% end -%>
 else
+<%# if any systemd services specified and is-enabled, loop through and restart them -%>
+<% if attributes[:deb_systemd_restart_after_upgrade?] -%>
+    echo Restarting <%= service %>
     $debsystemctl restart <%= service %> >/dev/null || true
 <% end -%>
 fi
 <% end -%>
 <% end -%>
+echo "Upgrade completed"
 }

 after_install() {
```

Checking who authored each line of change:

```
⓿ snickerdoodle(~/projects/fpm) pull/1714
% git diff -U0 $(git merge-base master HEAD) | awk '/^@@/ { print $3 }' | tr -d + | awk -F, '{print $1, $1+$2}' | xargs -n2 sh -c 'PAGER=cat git annotate -L $1,$2 templates/deb/postinst_upgrade.sh.erb' -
b202adb1        ( Derek Lee     2020-06-22 10:06:44 +1200       16)if ! systemctl is-enabled <%= service %> >/dev/null
d7b46678        (  c-ameron     2019-03-17 20:27:22 +1300       25)    $debsystemctl restart <%= service %> >/dev/null || true
f92427dc        (Jens Peter Schroer     2015-09-08 14:10:23 +0200       26)<% end -%>
fe6b381f        ( Derek Lee     2020-08-13 09:16:34 +1200       27)else
fe6b381f        ( Derek Lee     2020-08-13 09:16:34 +1200       28)<%# if any systemd services specified and is-enabled, loop through and restart them -%>
fe6b381f        ( Derek Lee     2020-08-13 09:16:34 +1200       29)<% if attributes[:deb_systemd_restart_after_upgrade?] -%>
57d42886        ( Derek Lee     2020-08-13 09:42:15 +1200       30)    echo Restarting <%= service %>
fe6b381f        ( Derek Lee     2020-08-13 09:16:34 +1200       31)    $debsystemctl restart <%= service %> >/dev/null || true
57d42886        ( Derek Lee     2020-08-13 09:42:15 +1200       36)echo "Upgrade completed"
```

**Comment by guohaolee** [comment]
Hi Jordan, thanks for the update.. i'll see how to resolve that merge conflict. 
Maybe someone else made the changes but I'll probably do a rebase etc..

Cheers.

**Comment by beberlei** [comment]
This was fixed with https://github.com/jordansissel/fpm/commit/72a925b048053f226eacd88b7ce2558e41b722db and is released in v1.13

**Comment by jordansissel** [comment]
@beberlei Thanks for noting that this was fixed <3

**Pull request closed without merging**
