### PR TITLE
DO NOT MERGE YET - .deb: Handle semver conversion when only one digit is present

### PR DESCRIPTION
**Pull request by torrancew**
Currently, if a gem has a semantic version requirement on a single digit number (aka "~> 3"), FPM winds up converting this into (in debian, at least) ">= 3" and "<< 0", which is obviously not satisfiable. The fix is fairly straightforward, but there is a test I've not yet figured out how to satisfy.

### CODE REVIEW

**Comment by torrancew** [comment]
@thedrow Yes! I have let this slip for far too long, and will revisit ASAP.

**Comment by josephholsten** [comment]
@torrancew anything we can do to help?

**Comment by josephholsten** [comment]
@torrancew I've rebased this in #1380, would love your review!

**Comment by torrancew** [comment]
Closing as stale

**Pull request closed without merging**
