### PR TITLE
Add --rpm-systemd option

### PR DESCRIPTION
**Pull request by mohd-akram**
I've inlined the systemd macro definitions as Ubuntu doesn't have them.

### CODE REVIEW

**Comment by jordansissel** [comment]
I am in favor of this, so thank you for contributing :)

I haven't tested or reviewed this, yet. Anyone willing to help test and provide feedback would be lovely. I'll try to make time to review+test this week.

**Comment by primalmotion** [comment]
I'm using this patch for a while and I have no issue at all. Works perfectly

**Comment by Niyakiy** [comment]
@jordansissel It would be nice to have this PR merged to cover missing functionality.

**Comment by olegmd** [comment]
We did not encounter any issues with it. @jordansissel this feature is vital for our internal CD process.

**Comment by sevagh** [comment]
Confirmed that this PR works well for me.

**Comment by kelu27** [comment]
up

**Comment by ericrange** [comment]
please merge

**Comment by trunet** [comment]
please merge

**Comment by Felixoid** [comment]
Is there any chance to get it merged?

**Comment by a-martynovich** [comment]
please merge

**Comment by jordansissel** [comment]
Code looks good. Small note that some of the RPM spec parts are outside of my knowledge. I see merge conflicts in git due to this change. Hopefully the conflicts are easy to resolve?

**Comment by jordansissel** [comment]
(I spent a bit working on the merge conflicts and then busted my ruby
environment badly so I’ll resume another day 😂)

**Comment by mohd-akram** [comment]
I've rebased the PR.

**Comment by jeanpralo** [comment]
Any chance you could have another look at it @jordansissel  ? 

That would be amazing as I suppose most people have to hack around the --after-install to be platform specific when they build packages for  debian and redhat based platforms.

Thanks for the work :)

**Comment by a-martynovich** [comment]
This PR needs some additional work to support systems timers. Right now they are treated incorrectly if I specify `--rpm-systemd my.timer` the file will be installed as `my.timer.service` and the install script will attempt to start it which will obviously fail. Also I found out that reinstalls (upgrades, downgrades) are not handled correctly. I have to manually enable and start the service after (re)installation. But with a couple of simple scripts (post-install, pre-remove, post-upgrade) I was able to make everything work correctly.

I'm currently out of job and I'm willing to contribute, only I need to know how to do it. Should I open a PR to mohd-akram:rpm-systemd? Or should I fork it, edit a copy of the branch and open a PR to jordansissel:master? Or something else?

**Pull request closed without merging**
