### PR TITLE
Documentation Changes

### PR DESCRIPTION
**Pull request by gamemaker1**
### Hi!

Hi there! First off, thanks to all the contributors for creating such a wonderful tool! I have used FPM for many of my projects, and I thought I might express my thanks by giving back to the community.

### What this PR changes

I noticed that the docs were a bit incomplete - though installation instructions were pretty clear, there was no actual tutorial/getting started guide. This PR aims to add a bit of introductory material to the [FPM docs](https://fpm.readthedocs.io).

Changes made:

- Rewrote some parts of the [installation page](/gamemaker1/fpm/tree/master/docs/installation.rst).
- Added a [getting started page](/gamemaker1/fpm/tree/master/docs/getting-started.rst).
 	* Added a tutorial to package a simple bash script and man page, which explains most of the basic flags one would use in FPM.
	* Merged most examples for sources like python, CPAN and npm into this page.
 	* Added a section documenting the `.fpm` configuration file.
- Added a [CLI reference page](/gamemaker1/fpm/tree/master/docs/cli-reference.rst) detailing all the options you can use with the CLI tool.

### Related issues

#1744 #1718

### Screenshots of the new documentation

<details>
<summary>Landing/Index page</summary>

fpm-docs-index-page

</details>

<details>
<summary>Installation page</summary>

fpm-docs-install-page

</details>

<details>
<summary>Getting started page</summary>

fpm-docs-getting-started-page

</details>

<details>
<summary>CLI reference page</summary>

fpm-docs-cli-reference-page

</details>

<details>
<summary>Contributing page</summary>

fpm-docs-contributing-page

</details>

---

Please do let me know if there can be any improvements to the changes made in this PR. Also let me know if some of these changes should be added to the Github Wiki for this project?

Thanks and regards!

### CODE REVIEW

**Comment by jordansissel** [comment]
I read through this and the screenshots on my phone, and it looks great!
I’ll get you some more detailed feedback (and/or merging it) once I’m at a
computer.

Thank you for spending time to make fpm better for others :)

**Comment by gamemaker1** [comment]
Sure, thanks!

**Comment by jordansissel** [comment]
I like the way this restructures the documentation and also provides a few good examples. Nice work :)

I have some ideas for generating the "cli-reference" page automatically from the code, and I'll try to get to that soon.

Thanks again for improving fpm for folks!

**Comment by gamemaker1** [comment]
> I have some ideas for generating the "cli-reference" page automatically from the code, and I'll try to get to that soon.

I did it using VSCode's multiple cursors feature and some manual formatting; a programmatic solution would be great!

> I like the way this restructures the documentation and also provides a few good examples. Nice work :)

Thanks!

**Comment by jordansissel** [comment]
> using VSCode's multiple cursors feature

Clever!

I merged the automated cli docs stuff a few moments ago. I probably missed
a few formatting or other issues, though.

Would love your feedback if you can:
https://fpm.readthedocs.io/en/latest/cli-reference.html

**Comment by gamemaker1** [comment]
It looks great; one thing I noticed was some flag names were not properly formatted as code:

image

Perhaps it is because of the trailing space after the options, maybe calling `strip!` on the flags and options might fix that.

**Comment by gamemaker1** [comment]
Here's a diff to fix that issue:

```diff
diff --git a/docs/generate-cli-reference.rb b/docs/generate-cli-reference.rb
index 84f71c6..0ed8b54 100644
--- a/docs/generate-cli-reference.rb
+++ b/docs/generate-cli-reference.rb
@@ -18,13 +18,13 @@ FPM::Command.instance_variable_get(:@declared_options).each do |option|
 
     if option.type == :flag
         # it's a flag which means there are no parameters to the option
-        puts "* ``#{option.switches.first}``"
+        puts "* ``#{option.switches.first.strip}``"
     else
-        puts "* ``#{option.switches.first} #{option.type}``"
+        puts "* ``#{option.switches.first} #{option.type.strip}``"
     end
 
     if option.switches.length > 1
-        puts "    - Alternate option spellings: ``#{option.switches[1..].join(", ")}``"
+        puts "    - Alternate option spellings: ``#{option.switches[1..].join(", ").strip}``"
     end
     puts "    - #{text}"
     puts
@@ -42,9 +42,9 @@ FPM::Package.types.sort_by { |k,v| k }.each do |name, type|
 
     options.sort_by { |flag, _| flag }.each do |flag, param, help, options, block|
         if param == :flag 
-            puts "* ``#{flag.first}``"
+            puts "* ``#{flag.first.strip}``"
         else
-            puts "* ``#{flag.first} #{param}``"
+            puts "* ``#{flag.first} #{param.strip}``"
         end
 
         text = help.sub(/^\([^)]+\) /, "")
```

**Comment by gamemaker1** [comment]
Also, the output-type-specific options have been nicely divided into their own sub-sections as well; but they still appear under General options.

**Comment by gamemaker1** [comment]
Diff for both the above fixes:

```diff
diff --git a/docs/generate-cli-reference.rb b/docs/generate-cli-reference.rb
index 84f71c6..b2e9afb 100644
--- a/docs/generate-cli-reference.rb
+++ b/docs/generate-cli-reference.rb
@@ -12,22 +12,26 @@ puts
 
 puts "General Options"
 puts "---------------"
+puts
 
 FPM::Command.instance_variable_get(:@declared_options).each do |option|
     text = option.description.gsub("\n", " ")
 
-    if option.type == :flag
-        # it's a flag which means there are no parameters to the option
-        puts "* ``#{option.switches.first}``"
-    else
-        puts "* ``#{option.switches.first} #{option.type}``"
-    end
+    # Don't show output-format-specific options, they get their own section
+    if !text.include? "only)"
+        if option.type == :flag
+            # it's a flag which means there are no parameters to the option
+            puts "* ``#{option.switches.first.strip}``"
+        else
+            puts "* ``#{option.switches.first} #{option.type.strip}``"
+        end
 
-    if option.switches.length > 1
-        puts "    - Alternate option spellings: ``#{option.switches[1..].join(", ")}``"
+        if option.switches.length > 1
+            puts "    - Alternate option spellings: ``#{option.switches[1..].join(", ").strip}``"
+        end
+        puts "    - #{text}"
+        puts
     end
-    puts "    - #{text}"
-    puts
 end
 
 FPM::Package.types.sort_by { |k,v| k }.each do |name, type|
@@ -42,9 +46,9 @@ FPM::Package.types.sort_by { |k,v| k }.each do |name, type|
 
     options.sort_by { |flag, _| flag }.each do |flag, param, help, options, block|
         if param == :flag 
-            puts "* ``#{flag.first}``"
+            puts "* ``#{flag.first.strip}``"
         else
-            puts "* ``#{flag.first} #{param}``"
+            puts "* ``#{flag.first} #{param.strip}``"
         end
 
         text = help.sub(/^\([^)]+\) /, "")
```

My fork has these changes, let me know if I should open a PR. Thanks!

**Pull request merged**
