### PR TITLE
Support RPM dist tag

### PR DESCRIPTION
**Pull request by adamonduty**
When --rpm-dist is specified, pass the dist tag to rpmbuild and
correctly name the file to ensure packages can be built with a
specific distribution in mind.

### CODE REVIEW

**Comment by jordansissel** [comment]
@adamonduty @alanthing Thanks for your notes on why you want this feature. I agree with you now. :)

Let's get the rpm-dist-specific code moved into just the rpm package, and I'll be happy to merge the feature.

**Comment by adamonduty** [comment]
Awesome! I'll move that code and get back to you in a day or two.

**Comment by adamonduty** [comment]
@jordansissel code was updated according to your comments. Also I added a test to preserve the behavior mentioned by @beddari.

**Comment by adamonduty** [comment]
I can squash the commits and/or rebase with master if it would make it easier to merge.

**Comment by areese** [comment]
I need the rpm-dist tag as well, is there anything else left to merge this?

**Comment by beddari** [comment]
Bump :) @adamonduty thanks for adding that test, lets hope we get a merge soon.

**Comment by jordansissel** [comment]
Code LGTM.

**Comment by jordansissel** [comment]
Tests pass. LGTM. Merging

**Comment by jordansissel** [comment]
Thanks to all who helped review and test this improvement! <3

@adamonduty thank you for your efforts :)

**Comment by areese** [comment]
@adamonduty thank you for your efforts as well, I can't wait to remove my hack around this.  :)

**Comment by jordansissel** [comment]
I'll try to get a new release of fpm out today.

**Pull request merged**
