### PR TITLE
Initial work on fpm docs with sphinx and 

### PR DESCRIPTION
**Pull request by jordansissel**
Docs published here: http://semicomplete.com/projects/fpm/index.html

This is a major work in progress and this PR exists as a way to jumpstart work on the docs for fpm.

### CODE REVIEW

**Comment by nicobrevin** [comment]
Want some help? Any sections or anything you want contributions for?

**Comment by jordansissel** [comment]
@nicobrevin any help would be so lovely! Some ideas:

* Review existing content for accuracy, confusion, or typos.
* Add docs for undocumented things (lots of work in this area):
  * Like: rpm output
  * The template features of `-p` flag (NAME, ARCH, etc)
  * Example use cases
  * Real-world uses (links to external projects)

**Comment by nicobrevin** [comment]
Roger, I might dip my toes tonight (nzdt)

**Comment by nicobrevin** [comment]
Something weird going on with make and my fu is weak:

```
make 
Makefile.sphinx:11: *** recipe commences before first target.  Stop.
```

**Comment by jordansissel** [comment]
@nicobrevin I fixed that a short while ago. Can you try again?

**Pull request merged**
