### PR TITLE
Fixed RPM spec file to not include 2 %pre tags, but 1 %pre and 1 %post

### PR DESCRIPTION
**Pull request by bbruun**
A fix for enabling --before-upgrade and --after-upgrade in the template/rpm.erb file which included 2 %pre tags where the second should be %post.

### CODE REVIEW

**Comment by hho** [comment]
I hit this as well. Duplicated by #830 (same fix, different bug description).

**Comment by robertwatson3** [comment]
Why isn't this merged?

**Comment by jordansissel** [comment]
I think https://github.com/jordansissel/fpm/commit/f6720c82d659bc44b52c833f5b447e375eadaeb2 fixed this, right?

**Comment by josephholsten** [comment]
@bbruun I think @jordansissel is right, should be fixed in f6720c82d659bc44b52c833f5b447e375eadaeb2. I'm closing, but please reopen if you think I'm wrong. I'm often wrong.

**Pull request closed without merging**
