### PR TITLE
add basic systemd service option

### PR DESCRIPTION
**Pull request by rhelmer**
It'd be nice to have an option as simple as e.g. `--rpm-init` for installing systemd services, especially when using source types other than `dir`, like `python`.

The service unfortunately needs to be activated/deactivated separately (I am doing this in `after-install` and `after-remove`), but it's pretty simple at least and works with all source types.

### CODE REVIEW

**Comment by phrawzty** [comment]
:+1:

**Comment by jordansissel** [comment]
Any chance you're interested in waiting on https://github.com/jordansissel/fpm/issues/856 or similar implementation?

**Comment by rhelmer** [comment]
@jordansissel pleaserun integration would be great!

Incidentally, it turns out I can't really use this for what I was planning, since I need to drop in config files to ```/etc``` and also set them as config files... I can't figure out a way to do this with ```python``` source type so I dropped back to using the ```dir``` source type.

**Comment by jordansissel** [comment]
For clarity on #856, my intention is to have pleaserun fully supported in fpm.

At first implementation, this will require you to make two packages. One for your app, one using pleaserun support. Second phase is some way to chain package creation to say "Package X is python Django + my app directory + pleaserun systemd"

**Comment by josephholsten** [comment]
@jordansissel @rhelmer I'm guessing it's not valuable for me to rebase this, would be better to implement #856, right? Should we close this?

**Comment by jordansissel** [comment]
@josephholsten agreed. pleaserun support was added in May 2016; I forgot to close #856 (just did now).

**Comment by jordansissel** [comment]
fpm supports `-s pleaserun` which lets you create a package with a service definition (systemd, upstart, etc) that is automatically detected at package-install time -- I think we can close this

**Pull request closed without merging**
