### PR TITLE
added set -e to debian maintainer scripts #1696

### PR DESCRIPTION
**Pull request by root360-AndreasUlm**
Signed-off-by: Andreas Ulm <andreas.ulm@root360.de>

### CODE REVIEW

**Review by BartKoppers — COMMENTED** [review]
See [Why doesn't set -e (or set -o errexit, or trap ERR) do what I expected?](http://mywiki.wooledge.org/BashFAQ/105). Also set -e is bash-specific. 
If accepted then at least a check is needed if  /bin/sh is linked to Bash. 
Or is /bin/sh on Debian *guaranteed* to be bash?

**Comment by root360-AndreasUlm** [comment]
> See [Why doesn't set -e (or set -o errexit, or trap ERR) do what I expected?](http://mywiki.wooledge.org/BashFAQ/105). Also set -e is bash-specific.
> If accepted then at least a check is needed if /bin/sh is linked to Bash.
> Or is /bin/sh on Debian _guaranteed_ to be bash?

@BartKoppers 
The shell option 'errexit' which is activated when `set -e`is executed is supported by all modern POSIX-compliant shells [1] and is not a Bash-only feature.
Debian uses sind a long time Dash as default shell.

As this PR changes only scripts used to create Debian Packages and Debian will always use POSIX-compliant shells there is no check necessary.

[1]:
* zsh https://linux.die.net/man/1/zshoptions (option ERR_EXIT)
* dash https://linux.die.net/man/1/dash (option errexit)
* csh https://linux.die.net/man/1/csh (option -e)
* tcsh https://linux.die.net/man/1/tcsh (option -e)
* ksh https://linux.die.net/man/1/ksh (option -e)
* etc.

**Comment by BartKoppers** [comment]
Discussion in issue #1696

**Review by BartKoppers — APPROVED** [review]

**Comment by jordansissel** [comment]
Thanks for the thoughtful discussion and improvement here. <3

**Pull request merged**
