### PR TITLE
turn osx tests on

### PR DESCRIPTION
**Pull request by stephengroat**

### CODE REVIEW

**Comment by jordansissel** [comment]
Hmm... Travis waiting ~1.5 hours for the mac jobs to start? Weird.

I see a few test failures for linux, but these are unrelated to this PR.

**Comment by stephengroat** [comment]
travis killed it's public/open source mac capacity, that's pretty much the new standard. I've seen 3hrs+ recently

i'm waiting for these to come back, but the `brew update && brew bundle` system has been working well for me on travis and it allows macOS dependency management outside of `.travis.yml`, which is nice

**Comment by jordansissel** [comment]
@stephengroat I'm open to merging without waiting for travis. You good with that? Or I can wait until later today.

**Comment by stephengroat** [comment]
@jordansissel some of the `ruby` versions don't work on `osx`, I was going to exclude them from the build matrix. to avoid a second pull request, could you wait?

i'll ping this pr when it looks good, don't want to waste your time

**Comment by jordansissel** [comment]
Cool -- I'll watch email for notification :)

**Pull request merged**
