### PR TITLE
adding option to add a systemd service file for a deb package.

### PR DESCRIPTION
**Pull request by jensschroer**
This pull request adds an option to provide a systemd service file in a deb package. It is inspired by the upstart option. 
fpm also generates the commands to install / uninstall the service

### CODE REVIEW

**Comment by jensschroer** [comment]
@jordansissel any chance to take a look at this? Given Debian's migration to systemd this might be a usefull feature for many.

**Comment by jordansissel** [comment]
@jensschroer agreed it is useful. This has merge conflicts, can you resolve them?

(Sorry for the delay in responding to you)

Also, thank you for improving fpm!

**Comment by jensschroer** [comment]
@jordansissel no problem. resolved the merge conflicts. mind to check once more?

**Comment by jordansissel** [comment]
Boom. Merged! :)

**Pull request merged**
