### PR TITLE
fix condition where the output directory's mode is 0700

### PR DESCRIPTION
**Pull request by rodriguezsergio**
I've run into a strange case where `fpm` on one of our jenkins builds outputs our project as $Project.dir with a mode of 775, but another project with an almost identical set of build instructions is creating a $Project.dir with a mode of 700.

I scanned the code really quick, but haven't quite found the source of the problem. I even tried to beat `fpm` to the punch and created the target directory so it would not have to run `mkdir` for me, and it still ended up overriding the mode with 700.

Ordinarily, this wouldn't be an issue, but the build is running with sudo and so the jenkins user cannot `cd` into that directory. If there's a better way to address this, or if you can point in the right direction, I'd certainly appreciate that.

### CODE REVIEW

**Comment by jordansissel** [comment]
Permissions issues usually are caused by `umask` settings for the user or process running fpm, but I agree that fpm should try and dodge that where possible.

**Comment by jordansissel** [comment]
I wonder if fpm could set umask(0777) on startup and that would help with this?

**Comment by jordansissel** [comment]
I just did some maintenance on the git history in the fpm repo. In doing so, I messed up this PR. You may have to rebase against master. Let me know if you need help doing this.

**Comment by jordansissel** [comment]
I just did some maintenance on the git history in the fpm repo. In doing so, I messed up this PR. You may have to rebase against master. Let me know if you need help doing this.

**Comment by rodriguezsergio** [comment]
Been meaning to get around to this. I'll see about rebasing against master this week.

**Comment by rodriguezsergio** [comment]
@jordansissel Okay, I think I found myself a better, more generic solution. How's this?

**Comment by josephholsten** [comment]
Looks like the failing tests are:
```
  1) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /usr
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  2) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /usr/bin
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  3) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /usr/lib
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 448, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  4) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /usr/share
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  5) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /usr/share/doc
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  6) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /etc
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  7) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /var
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  8) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /var/lib
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'

  9) FPM::Package::Pacman#output normal tests file permissions should preserve file permissions for /var/lib/foo
     Failure/Error: dir)).mode & 07777 } == perm
     Insist::Failure:
       Expected 493, but got 509
     # ./spec/fpm/package/pacman_spec.rb:212:in `block (6 levels) in <top (required)>'
```

**Comment by josephholsten** [comment]
short version, the pacman test for perms `Expected 493, but got 509`

**Pull request closed without merging**
