### PR TITLE
rpm: add option to enable install-time macro expansion in scripts

### PR DESCRIPTION
**Pull request by juliantrzeciak**
- spec file sections affected: %pre %post %preun %postun

### CODE REVIEW

**Comment by CsatariGergely** [comment]
@jordansissel do we need to fix Travis before this can be merged? The errors seem to be unrelated to the change.

**Comment by jordansissel** [comment]
Depends on the failures, but Travis is usually failing unrelated to any PR
for reasons I haven’t figured out (and they pass locally for me).

I don’t think I’ve evaluated this PR yet, and any additional testing and
user feedback is welcome :)

**Comment by CsatariGergely** [comment]
@jordansissel thanks for the answer. Do you know when will you have time to evaluate this pr?

**Comment by CsatariGergely** [comment]
@jordansissel any update?

**Comment by CsatariGergely** [comment]
@jordansissel can you please suggest a way forward to get this merged? Are there other contributors who should review this change?

**Comment by jordansissel** [comment]
@CsatariGergely if you are able to test this and report findings (works as expected, needs improvements, doesnt work, etc), that would be helpful. I'll see about testing this sometime this month, sorry for delays.

**Comment by CsatariGergely** [comment]
@juliantrzeciak can you acknowledge, that his was tested and working?

**Comment by juliantrzeciak** [comment]
tested manually, works as expected, Thanks!

**Comment by CsatariGergely** [comment]
@jordansissel What else is needed to get this merged?

**Comment by CsatariGergely** [comment]
Thanks for merging.

**Pull request merged**
