### PR TITLE
Fixes #1206 Improved download URL query for CPAN modules

### LINKED ISSUE #1206: [BUG] Wrong author used to query CPAN API for some old versions of CPAN modules
Steps to reproduce:

```bash
fpm -s cpan -t rpm --version 0.08196 --no-cpan-sandbox-non-core --no-cpan-test --debug --debug-workspace 'DBIx::Class'
```
Error produced:

```
metacpan release query failed. {:error=>"404 \"Not Found\"", :url=>"http://api.metacpan.org/v0/release/RIBASUSHI/DBIx-Cl
ass-0.08196", :level=>:error, :file=>"fpm/package/cpan.rb", :line=>"327", :method=>"rescue in download"}
Invalid package configuration: metacpan release query failed {:level=>:error, :file=>"fpm/command.rb", :line=>"488", :me
thod=>"rescue in execute"}
```

This is because  the author has changed between module versions and the author is queried using latest version (I think).

### PR DESCRIPTION
**Pull request by liger1978**
- Added httppost function to cpan.rb
  - Determine correct archive download URL using metacpan API search (using POST request). More reliable than previous GET method (see issue #1206).

### CODE REVIEW

**Comment by liger1978** [comment]
Failing CI is again only down to the Travis Mac hosts being unavailable...

**Comment by liger1978** [comment]
Please can someone review this merge request?  The failing CI is due to Travis CI Mac hosts being down rather than the code change.

**Comment by liger1978** [comment]
Bump.

**Comment by jordansissel** [comment]
Code looks OK. Tests are green (I'm ignoring the OSX failures, they fail frequently anyway)

**Pull request merged**
