### PR TITLE
Add package metadata to slug file format

### PR DESCRIPTION
**Pull request by gerbercj**
We're starting to use the SH package format for a number of different project types. As part of this, we're adding some metadata to the packages so that we can easily determine how to deploy them. For example, a Rails project will want to roll unicorns, but a package of JavaScript assets would be installed differently. For other users, this is a no-op, with the exception of seeing a new `__METADATA__` line in the file, just prior to the `__ARCHIVE__` line.
@jordansissel

### CODE REVIEW

**Comment by gerbercj** [comment]
@jordansissel, any concerns with this enhancement to our package format?

**Comment by jordansissel** [comment]
Nope! Patch reads OK to me. Any thoughts on tests?

**Comment by gerbercj** [comment]
Totally reasonable request. Let me see what I can do for tests (in between shoveling breaks :snowflake:).

**Comment by jordansissel** [comment]
Tests pass <3

**Comment by jordansissel** [comment]
Sorry for the delay in attending to this. <3

**Pull request merged**
