### PR TITLE
remove trailing slash from --prefix option #819

### PR DESCRIPTION
**Pull request by dhajoshi**

### CODE REVIEW

**Comment by jordansissel** [comment]
Any thoughts on adding tests for this?

**Comment by dhajoshi** [comment]
yup, i will do that, it just i am learning ruby and have not added any test, will add for this by looking at other tests. Thanks

**Comment by luto** [comment]
If all goes well this has been superseeded by https://github.com/jordansissel/fpm/issues/1137 and can be closed. Thank you @dhajoshi for your initial code and report :+1:

**Comment by josephholsten** [comment]
I'm closing this, but me know if I'm wrong.

**Pull request closed without merging**
