### PR TITLE
Remove old rubies

### PR DESCRIPTION
**Pull request by vjanelle**

### CODE REVIEW

**Comment by vjanelle** [comment]
On mac, it fails because `error: Macro %buildroot has empty body`, which is curious.

**Comment by vjanelle** [comment]
On mac:

````
warning: Macro expanded in comment on line 24: %undefine __check_files

Executing(%prep): /bin/sh -e /var/folders/d0/wnbv5gcd3t5462k0npj_w4n80000gn/T/rpm-tmp.0CNa4I
Executing(%build): /bin/sh -e /var/folders/d0/wnbv5gcd3t5462k0npj_w4n80000gn/T/rpm-tmp.5xMrQr
Executing(%install): /bin/sh -e /var/folders/d0/wnbv5gcd3t5462k0npj_w4n80000gn/T/rpm-tmp.pZgfvf
Processing files: foo-1.0-1.x86_64
error: File not found: /var/folders/d0/wnbv5gcd3t5462k0npj_w4n80000gn/T/package-rpm-build-42750e305e2ca70f71c23ef8f30499b7b937a644a5e198143d366cc63302/BUILD/Users/random/rpmtest/foo[\[]bar[\]]blah


RPM build errors:
    Macro expanded in comment on line 24: %undefine __check_files

    File not found: /var/folders/d0/wnbv5gcd3t5462k0npj_w4n80000gn/T/package-rpm-build-42750e305e2ca70f71c23ef8f30499b7b937a644a5e198143d366cc63302/BUILD/Users/random/rpmtest/foo[\[]bar[\]]blah
```

**Comment by vjanelle** [comment]
Looks like fpm is generating the file with the wrong contents.  The macro expansion is because of a regression in rpmbuild.

**Comment by vjanelle** [comment]
@jordansissel the only thing I can really think of is to special case darwin in `rpm_fix_files`.  :\

**Comment by jordansissel** [comment]
> error: File not found: /var/folders/d0/wnbv5gcd3t5462k0npj_w4n80000gn/T/package-rpm-build-42750e305e2ca70f71c23ef8f30499b7b937a644a5e198143d366cc63302/BUILD/Users/random/rpmtest/foo[\[]bar[\]]blah


I'll test this on my workstation. Maybe newer rpms changed how globs are handled. These test cases are for allowing reserved/special characters in filenames and most of the time it's just a guess as to what works.

**Comment by vjanelle** [comment]
@jordansissel the other thing that just popped into mind:

On MacOS X:

/bin/bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin19)

On Ubuntu:

```
docker run -it --rm ubuntu bash
root@4a20879e0533:/# /bin/bash --version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
```

Centos:

```
docker run -it --rm centos bash
[root@1b2a45ef4461 /]# /bin/bash --version
GNU bash, version 4.2.46(2)-release (x86_64-redhat-linux-gnu)
```

RPM generates a shell script at some point right?  Is the globbing different?

**Comment by jordansissel** [comment]
It does but not for files listing I think? Hmm... I still haven’t made time
to explore this.

**Comment by vjanelle** [comment]
@jordansissel woke up from a nap and thought that could be it, but when I looked at the bash scripts generated I doh'd.

I did see something in the past about letting "rpm deal with it" wrt to file globbing, in that you don't generate the spec with every single file in it, but I lost which tab that was in. :\

**Comment by jordansissel** [comment]
This is still on my todo to test and evaluate. I haven't found energy yet.

**Pull request closed without merging**
