### PR TITLE
deb: explicitly chmod triggers to 0644 for lintian

### PR DESCRIPTION
**Pull request by fasterthanlime**
:star2: Should fix https://github.com/itchio/itch/issues/93 :bug:

### CODE REVIEW

**Comment by fasterthanlime** [comment]
Can confirm this did fix https://github.com/itchio/itch/issues/93 for us!

**Comment by fasterthanlime** [comment]
Still a good fix :+1:

**Comment by fasterthanlime** [comment]
Would still love this merged as I need to maintain our fork as long as it's not :(

**Comment by jordansissel** [comment]
LGTM

**Pull request merged**
