### PR TITLE
Update fpm.rb

### PR DESCRIPTION
**Pull request by faraazahmad**
Remove the explicit requiring of all the packages. Instead, add a small snippet to automatically require all the packages in the package directory.

### CODE REVIEW

**Comment by jordansissel** [comment]
I think I understand the proposal, but I am not sure what the benefit is - Can you tell me why you want this change?

**Comment by faraazahmad** [comment]
It reduces the number of lines of code and you don't have to worry about ```require```ing new files explicitly. They'll be automatically included. If it's not a helpful feature, you can close the issue. ✌️

**Comment by jordansissel** [comment]
In testing this patch, I find it doesn't appear to work?

```
% pwd
/home/jls/projects/fpm

% bin/fpm --help
/home/jls/projects/fpm/lib/fpm.rb:5:in `open': No such file or directory @ dir_initialize - fpm/package (Errno::ENOENT)
```

**Comment by faraazahmad** [comment]
Can you show the code? You may have to use ```require_relative``` instead of ```require```

**Comment by faraazahmad** [comment]
I think I'll have to ```require_relative```

**Comment by josephholsten** [comment]
I'm not sure we really want this, for the same reasons `autoload` is being deprecated: https://bugs.ruby-lang.org/issues/5653

**Comment by jordansissel** [comment]
Interesting thread on ruby-lang. I've never wanted Autoload, but it's cool that Autoload is thread-safe in JRuby, but maybe still not safe in MRI? FPM itself doesn't use threads right now, so maybe it's not an issue.

Personally, a long list of requires doesn't bother me much. I think we could close this or fix it to work -- either is fine with me.

**Comment by jordansissel** [comment]
I don't know exactly what happened here. I renamed the `master` branch to `main` and GitHub closed this automatically as a side effect. It won't let me reopen it. It looks like the branch for this PR has been deleted by the author and GitHub got very confused about what to do? Sorry for the noise.

**Pull request closed without merging**
