### PR TITLE
Drop leading v from version for Debian

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

#1847

### CODE REVIEW

**Comment by jordansissel** [comment]
Thanks for working on this!

I think there's a few other places that use the 'version' field. I recommend, instead of modifying the deb.changes template, overriding the 'version' method as fpm does in the rpm.rb, shown here:

https://github.com/jordansissel/fpm/blob/db06af3c0357e212df48009ecd73c945519a1e76/lib/fpm/package/rpm.rb#L598-L606

Such a method `def version ... end` would go into `lib/packages/fpm/deb.rb`. This would allow any corrections to the version field to be used everywhere (the control file, deb.changes, etc)

**Comment by gliptak** [comment]
@jordansissel thank you for the pointer. updated

PS I'm not setup to test the project locally

**Comment by jordansissel** [comment]
> PS I'm not setup to test the project locally

No worries! I'll take care of testing :)

**Comment by jordansissel** [comment]
Looks good! Thank you :)

**Comment by jordansissel** [comment]
```
% fpm -s empty -t deb -v v1.2.3  -n example
Drop leading v from package version 'v1.2.3' {:level=>:warn}
Created package {:path=>"example_1.2.3_all.deb"}

# Verify the version
% dpkg -f example_1.2.3_all.deb Version
1.2.3
```

**Pull request merged**
