### PR TITLE
 Nuget support (re:#704)

### PR DESCRIPTION
**Pull request by josephholsten**
rebased #704

### CODE REVIEW

**Comment by josephholsten** [comment]
failing tests, and I don't know what I'm doing ¯\_(ツ)_/¯

**Comment by josephholsten** [comment]
@ringods I've rebased #704, but I don't really know what I'm doing. Was there anything in particular that was remaining for this? Or do I just need to fix the tests?

**Comment by josephholsten** [comment]
current failing tests:
```
  1) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:23:in `block (4 levels) in <top (required)>'
  2) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency 1'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:29:in `block (4 levels) in <top (required)>'
  3) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency 1.2'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:33:in `block (4 levels) in <top (required)>'
  4) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency 1.2.3'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:37:in `block (4 levels) in <top (required)>'
  5) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency [1.2.3]'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:41:in `block (4 levels) in <top (required)>'
  6) FPM::Package::Nuget #fix_dependency with normal versions should fail on 'MyDependency (1.2.3)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:45:in `block (4 levels) in <top (required)>'
  7) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency (,1.2]'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:49:in `block (4 levels) in <top (required)>'
  8) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency (,1.2.3)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:53:in `block (4 levels) in <top (required)>'
  9) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency (1.2,)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:57:in `block (4 levels) in <top (required)>'
  10) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency (1.2,2.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:61:in `block (4 levels) in <top (required)>'
  11) FPM::Package::Nuget #fix_dependency with normal versions should accept 'MyDependency [1.2,2.0]'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:65:in `block (4 levels) in <top (required)>'
  12) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency 1 2'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:72:in `block (4 levels) in <top (required)>'
  13) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency 1.2 (,2.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:76:in `block (4 levels) in <top (required)>'
  14) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency 1.2.3' (,2.0)
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:80:in `block (4 levels) in <top (required)>'
  15) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency [1.2.3]' (,2.0)
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:84:in `block (4 levels) in <top (required)>'
  16) FPM::Package::Nuget #fix_dependency with allowed versions should fail on 'MyDependency (1.2.3) (,2.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:88:in `block (4 levels) in <top (required)>'
  17) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency (,1.2] (,2.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:92:in `block (4 levels) in <top (required)>'
  18) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency (,1.2.3) (,2.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:96:in `block (4 levels) in <top (required)>'
  19) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency (1.2,) (,2.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:100:in `block (4 levels) in <top (required)>'
  20) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency (1.2,2.0) (,3.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:104:in `block (4 levels) in <top (required)>'
  21) FPM::Package::Nuget #fix_dependency with allowed versions should accept 'MyDependency [1.2,2.0] (,3.0)'
     Failure/Error: fail()
     RuntimeError:
     # ./spec/fpm/package/nuget_spec.rb:108:in `block (4 levels) in <top (required)>'
```

**Comment by ringods** [comment]
@josephholsten I'm sorry, but I'm no longer working on `fpm`, so I won't be able of much help.

**Comment by ajoslin103** [comment]
Perhaps a banner on the repo ReadMe requesting help with finishing this PR might get some traction?  As it is one has to dig to find this.

**Pull request closed without merging**
