### PR TITLE
Multiple debian systemd services

### LINKED ISSUE #1271: Providing several --deb-systemd files should be supported
If you add several --deb-systemd files they seem to get packaged correctly, but the `postinst` and `prerm` scripts only contain code referring to the last one.

### PR DESCRIPTION
**Pull request by diasjorge**
With this pull request I add support for multiple systemd services.

It fixes #1271

### CODE REVIEW

**Comment by diasjorge** [comment]
Is this something that would be interesting for the project? I think the failing tests are unrelated. We currently have a need for this for some of our packages and doing some manual workaround.

**Comment by jordansissel** [comment]
Seems like a good idea. I don’t think anyone’s made time to test and review
it.

**Comment by diasjorge** [comment]
@jordansissel I've added some tests to ensure the right postinst file is generated. Do you think that's a good approach for the test?

**Comment by subvertallchris** [comment]
I'd love to take advantage of this. Thanks for your work, @diasjorge.

**Comment by jordansissel** [comment]
I’ll try to review and test this this week.

**Comment by diasjorge** [comment]
I see you added some commits that address this same issue. I've rebased my work on top of the new master. Would you be interested in keeping the tests?

**Comment by subvertallchris** [comment]
Is this not happening now?

**Comment by chinmayprabhudesai** [comment]
@diasjorge and @jordansissel,

This PR is pending since a while, the latest release was just before this PR, is there a timeline to get this in ?

Thanks!

**Comment by jordansissel** [comment]
I haven’t been able to make time to review or test this yet. If others can
review or test this, that would help this get merged.

**Comment by diasjorge** [comment]
There was another change that got merged that added support for multiple systemd services. This PR was rebased on top and added tests for it

**Pull request closed without merging**
