### PR TITLE
CPAN test and sandboxing fixes

### PR DESCRIPTION
**Pull request by hatt**
As discussed in #515 and #748, make sandboxing optional for packaging with system dependencies. This doesn't fix the core issue with RHEL and derivatives, but it does allow users to not install every dependency if they want a build to use system installed modules.

Up til now, `--cpan-test` would skip tests when told to test and then run them when told not to. That was bad logic on my part I think, so this reverses the behavior and makes it do what a user would expect.

### CODE REVIEW

**Comment by satoshi** [comment]
@jordansissel is there a chance this pull request can be merged?  @hatt  has done some wonderful work on this and I'd like to see it incorporated into master.

**Comment by jordansissel** [comment]
+1 on the idea, sorry for the delays. @hatt, can you rebase against master? I'll work on merging after that.

**Comment by jordansissel** [comment]
Actually, I May be able to patch this in by hand now.

**Comment by hatt** [comment]
@jordansissel sorry, I just saw comment now, thanks for doing that for me!

**Pull request closed without merging**
