### PR TITLE
Fixing #564 by doing a chmod 0755 of the prefix directory after the c…

### PR DESCRIPTION
**Pull request by edgan**
…lone

### CODE REVIEW

**Comment by hatt** [comment]
I'm not sure if it's better to comment here or on #564 but since this is the PR, will keep it here. I think because Tar sources come from a Tmpdir, it's inheriting the permissions used somehow. `Dir::Tmpdir` defaults to 0700 (see `Dir.mktmpdir` in `tmpdir.rb` in Ruby core.

The clone method which looks to be bork is just calling copy which in turn sets 0755, or at least it should. I'm not sure the PR really fixes the source of the issue and why this is happening but it's a valid enough workaround.

**Comment by edgan** [comment]
My thought was the it could be argued that in general a 0700 on a temp directory isn't a bad policy. The code then directly clones the temp directory. So why not just fix it after the clone.

**Comment by hatt** [comment]
I think that makes sense but also wonder why the call to `copy(:mode => 0755)` isn't being applied properly...

**Comment by jordansissel** [comment]
I don't know exactly what happened here. I renamed the `master` branch to `main` and GitHub closed this automatically as a side effect. It won't let me reopen it. It looks like the branch for this PR has been deleted by the author and GitHub got very confused about what to do? Sorry for the noise.

**Pull request closed without merging**
