### PR TITLE
Nuget support

### PR DESCRIPTION
**Pull request by ringods**
Initial pull request to kickstart code review. This is still work in progress.

### CODE REVIEW

**Comment by jordansissel** [comment]
I realize I let this fall through the cracks! Sorry about that :)

@ringods anything I can help with on this? I totally understand if you haven't had time or energy to finish - I Just want to make sure I'm not blocking progress :)

**Comment by ferventcoder** [comment]
Ping @ringods - Is there a newer version of this somewhere?

**Comment by ringods** [comment]
@ferventcoder I haven't had time to update this, add tests, etc. Hard at work to get @releasequeue out on the market.

**Comment by ferventcoder** [comment]
Ah right on. Thanks!

**Comment by rnelson0** [comment]
Anyone have updates on this? This would be another amazing addition to FPM!

**Comment by ajoslin103** [comment]
this would be very helpful for me

**Comment by jordansissel** [comment]
I didn't mean to let this PR stagnate so badly.

I'll see about forking it to make it merge into master soon.

**Comment by jordansissel** [comment]
I don't know exactly what happened here. I renamed the `master` branch to `main` and GitHub closed this automatically as a side effect. It won't let me reopen it. It looks like the branch for this PR has been deleted by the author and GitHub got very confused about what to do? Sorry for the noise.

**Pull request closed without merging**
