### PR TITLE
Process PEP0508 markers on python package requirements

### PR DESCRIPTION
**Pull request by penguinolog**
Process PEP0508 markers on python package requirements

Closes-bug: #1307

### CODE REVIEW

**Comment by penguinolog** [comment]
No any changes over tests has been providden,
https://packaging.pypa.io/en/latest/markers/ was used as marker API description and https://setuptools.readthedocs.io/en/latest/pkg_resources.html#requirements-parsing as record API description.

Tested on example from bug description.

**Comment by jordansissel** [comment]
I confess that I don't quite understand what this fixes. For disclosure, I don't know what these 'markers' are or what problem is fixed by this patch. I read the parent issue (#1307) and did not reach much clarity.

This is ok, though. 

Code looks OK, but I'd like it if someone else with more recent python experience especially around this PEP-0508 area would review this.

Alternately, adding tests might help this get merged more quickly as the tests could help ensure this fix remains fixed.

**Comment by penguinolog** [comment]
@jordansissel Tests updated: added 2 requirements, 1 of which should be ignored.

**Comment by pohmelie** [comment]
@jordansissel 
This patch affect optional dependencies.
Real life example: python 3.5 introduced new module `typing`, which is backported as separate module to pypi. Dependency for third package may looks like:
```
install_requires=[
    'typing; python_version < "3.5"',
]
```
And installing this third package on python 3.5 or greater means, that this package have no external dependencies. The opposite case is when install on python 2.7 (for example), this third package should have `typing` dependency in result package metainformation.

Vote for this to be implemented with both hands! (can't review code, since I'm not familiar with ruby)

**Comment by penguinolog** [comment]
Main patch is implemented on python helper side and on Ruby side was updated unit tests only.

**Comment by pohmelie** [comment]
@penguinolog 
Do you mean this feature in upstream already?

**Comment by penguinolog** [comment]
@pohmelie no, I just explain languages of this PR

**Comment by papermakkusu** [comment]
Yo!
Code looks fine to me but I do not get the idea behind these changes. No surpriises here scince I'm not familiar with the code.

**Comment by jordansissel** [comment]
Given the feedback so far, I'm content to merge. The Travis-CI failures seem unrelated to this PR.

**Pull request merged**
