### PR TITLE
Lazily require xz at the last possible moment to avoid dependency on liblzma.so.5

### LINKED ISSUE #1090: Latest fpm 1.5.0 fails to install on CentOS6: "ruby-xz requires Ruby version >= 1.9.3"
Maybe there's an easy workaround? I tried first installing an older version of ruby-xz  `gem install ruby-xz -v 0.1.1` but that didn't help.
```
$ docker run -ti centos:centos6 bash
# yum groupinstall -y "Development tools"
# yum install -y make gcc gawk ruby-devel rubygems
# gem install fpm
ERROR:  Error installing fpm:
	ruby-xz requires Ruby version >= 1.9.3.
```

To workaround, use older version of fpm on CentOS6:
```
# gem install fpm -v 1.4.0
Successfully installed fpm-1.4.0
1 gem installed
```

### PR DESCRIPTION
**Pull request by ketan**
Fixes #1090

### CODE REVIEW

**Comment by ketan** [comment]
Can we get a 1.6.1 out once this is merged, please?

**Comment by jordansissel** [comment]
Sounds good to me :)

**Comment by jordansissel** [comment]
fpm 1.6.1 published.

**Comment by ketan** [comment]
Many thanks foe this awesome gem :)

**Pull request merged**
