### PR TITLE
Perl CPAN Support, Fix Broken PERL5LIB & Add cpanm Verbose Option

### PR DESCRIPTION
**Pull request by wbraswell**
Fixed https://github.com/jordansissel/fpm/pull/1510

### CODE REVIEW

**Comment by wbraswell** [comment]
@jordansissel 
sorry for the confusion, I just figured the fastest solution was to close the old pull request and open a new one with the fix

**Comment by jordansissel** [comment]
Thank you for working on this! Code change looks good. I am testing now :)

**Comment by jordansissel** [comment]
I tested manually the following:

`% bin/fpm --verbose --no-cpan-test -s cpan -t deb Alien::PCRE2`

* master: :x: fails as expected by #1509 
* this pr: ✔️ `Created package {:path=>"perl-alien-jpcre2_0.012000_all.deb"}`

Confirmed this fixes #1509 

The test suite (`rspec spec/fpm/package/cpan_spec.rb`) fails 1 of 3 tests, but this same failure happens on master, so I do not believe this PR caused any test failures.

LGTM :)

**Comment by jordansissel** [comment]
I'll prepare a release now.

**Pull request merged**
